package com.starzplay.payment.enums;

public enum Status {
    NEW,    //REQUEST IS NEW
    WARN, //
    SUCCESS, //REQUEST IS SUCCESSFUL
    FAILED, // REQUEST IS VALIDATED BEFORE EXECUTION AND IT IS FOUND TO BE NOT VALID,
    ERROR, // REQUEST EXECUTION FAILED
    EXC,// ANY OTHER EXCEPTION
    INITIATED
}
